cors:
    origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:5174,http://192.168.18.128:5173}
email:
    password-recover:
        token:
            minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:30}
        uri: ${PASSWORD_RECOVER_URI:http://localhost:5173/recover-password/}
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
security:
    client-id: ${CLIENT_ID:bookplaceid}
    client-secret: ${CLIENT_SECRET:bookplacepassword}
    jwt:
        duration: ${JWT_DURATION:86400}
spring:
    jpa:
        open-in-view: false
    mail:
        host: ${EMAIL_HOST:smtp.gmail.com}
        password: ${EMAIL_PASSWORD:1234567}
        port: ${EMAIL_PORT:587}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: ${EMAIL_USERNAME:teste@gmail.com}
    output:
        ansi:
            enabled: ALWAYS
    profiles:
        active: ${APP_PROFILE:test}

management:
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: refresh, health, info, metrics, prometheus, h2-console
    endpoint:
        refresh:
            enabled: true
        health:
            enabled: true
            show-details : always
        info:
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled : true

pagseguro:
    authorization-token: ${PAGSEGURO_AUTH_TOKEN}
